### PR TITLE
minor additions to theme color names

### PR DESCRIPTION
**Pull request by cstolli**
@sglanzer

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Cool beans - we noticed the hover/focus were the same for certain items a few days ago, so Phil may be making some adjustments, but happy to approve this.

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-theme/pull-request/26/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-theme)

**Comment by sandersky** [comment]
@cstolli needs merged with upstream

**Comment by sandersky** [comment]
Went ahead and opened up #33 to get this out

**Pull request closed without merging**
